### ISSUE TITLE
return_name

### ISSUE THREAD

**Issue by kewlfft** [rsheftel/pandas_market_calendars#1]
thanks for this project.
I am having difficulty getting back the name of the holiday corresponding to the dates returned in .holidays()
How can I get back the holiday name together with the date?

**Comment by rsheftel** [comment]
First thank you for liking the project.

The .holidays() method returns a pandas CustomBusinessDay() object with the combination of the regular and ad-hoc holidays. pandas doc here: http://pandas.pydata.org/pandas-docs/stable/timeseries.html#custom-business-days-experimental 

If you want to get the regular scheduled holidays you can call .regular_holidays which returns a pandas AbstractHolidayCalendar object. A call to .regular_holidays.rules will return all of the rules that comprise the holiday calendar. Pandas doc here: http://pandas.pydata.org/pandas-docs/stable/timeseries.html#holidays-holiday-calendars

A call to .adhoc_holidays will return a list of the dates, but since the adhoc_holidays could just be an list of pandas TimeStamps the names used to create them is not preserved in the call.

**Comment by kewlfft** [comment]
thanks very much for the clear explanations, by looking at mycal.regular_holidays.holidays("20170101", "20171231", return_name=True) I get the days with their names which is what I wanted. 
I am interested in future dates, as the AdHoc holidays are more about past days, in my case I am good ignoring them I think
