### ISSUE TITLE
date_range() has wrong validation for frequency

### ISSUE THREAD

**Issue by QARancher** [rsheftel/pandas_market_calendars#102]
Hi,
When using **_mcal.date_range(early, frequency='5D')_**, an error is raised:
**{ValueError}Frequency must be 1D or higher frequency.**

which is incorrect, the code has the following bug:
    if pd.Timedelta(frequency) > pd.Timedelta('1D'):
        raise ValueError('Frequency must be 1D or higher frequency.')

it should be 
    if pd.Timedelta(frequency) < pd.Timedelta('1D'):
        raise ValueError('Frequency must be 1D or higher frequency.')

**Comment by rsheftel** [comment]
The code is correct, the confusion may be with the nomenclature. In trading the term "higher frequency" means a lower time span. So 1 minute is a "higher frequency" than 1 Day. In pandas it is testing for the length of time, so if the requested time frequency is a lower (or shorter) number than 1 Day, then it is valid because that is a "higher frequency". You can see below that this check will return false for 1min, because that is a valid time frequency and should not raise the exception, but will return true and raise the exception for 1 week.

```
In [4]: pd.Timedelta('1min') > pd.Timedelta('1D')                                                                          
Out[4]: False

In [5]: pd.Timedelta('1W') > pd.Timedelta('1D')                                                                            
Out[5]: True
```

**Comment by QARancher** [comment]
thank you, should have dig in more
