### ISSUE TITLE
Possible bug in trading_calendars_mirror.py

### ISSUE THREAD

**Issue by jbtheming** [rsheftel/pandas_market_calendars#125]
This may well be intended behaviour, but as it stands the code to subtract one minute from the start time in `trading_calendars_mirror.py` only does this if the minute component of start time is greater than 0, which confused me for quite some time while implementing my first calendar in the trading_calendars project.

If it's not intended, then the return statement in `open_time_default` method could be changed from 

`return time(tc_time.hour, max(tc_time.minute - 1, 0), tzinfo=self.tz) `

to

`return time(tc_time.hour, (tc_time.minute - 1) % 60, tzinfo=self.tz) `

which will ensure that time(9, 0) will become (8, 59)

**Comment by jbtheming** [comment]
Actually that's a rubbish fix as the hour will then be wrong, but my observation still stands

**Comment by rsheftel** [comment]
The `trading_calendars.py` module provides the functionality to take the calendars in the https://github.com/quantopian/trading_calendars project and make them available in pandas_market_calendars. This is part of the transition plan to have trading_calendars be the main source for all calendars and this package as a wrapper around that. For more information on that roadmap see #120 

The reason for the subtraction of 1 minute from the calendars in trading_calendars is due to a legacy issue with that package that had to work with the Zipline project, see https://github.com/quantopian/trading_calendars#why-are-open-times-one-minute-late

Since that is not the correct open time, or break start time, this package corrects for that by subtracting a minute to get the proper start time, as the functions in this pandas_market_calendars do not need to support Zipline and thus can have the correct start time. You can look at any of the calendars in trading_calendars to see the open time is 1 minute after the real open.

But all of that is only for this package to bring in the trading_calendars calendars. Your comment is that you are making a new calendar in this package. In that case you will never encounter the `trading_calendars_mirror.py` module and thus can safely ignore it.

**Comment by jbtheming** [comment]
Ah OK, thanks. It confused me as I have been primarily using pandas_market_calendars, but have had to implement a couple of new calendars in trading_calendars because of specific functionality that only exists there. The puzzling behaviour did force me to step through a lot of the code though, so I consider it time well spent!
