### ISSUE TITLE
Some holidays are off

### ISSUE THREAD

**Issue by WladimirOstrovskyBitcap** [rsheftel/pandas_market_calendars#134]
Hi,

I found that some holidays are off. If I understand correctly, the daterange should be empty for the given days but it is not:

```
import pandas_market_calendars as mcal

exch = mcal.get_calendar('CBOT')
daterange = exch.valid_days(start_date=pd.to_datetime('2020-01-18'), end_date=pd.to_datetime('2020-01-18'))
print(daterange)  # print: DatetimeIndex(['2021-01-18 00:00:00+00:00'], dtype='datetime64[ns, UTC]', freq='C')

exch = mcal.get_calendar('HKEX')
daterange = exch.valid_days(start_date=pd.to_datetime('2020-04-06'), end_date=pd.to_datetime('2020-04-06'))
print(daterange)  # print: DatetimeIndex(['2021-04-06 00:00:00+00:00'], dtype='datetime64[ns, UTC]', freq='C')
```

Best
Wladimir

**Comment by rsheftel** [comment]
The CBOT calendar is very generic and will be deprecated in a future release. You are best to use a product specific CME calendar as documented here: https://pandas-market-calendars.readthedocs.io/en/latest/calendars.html#futures-calendars

For the HKEX, according to their web site, 2012-04-06 is a valid and open trading day. See the holiday calendar at the bottom of this web page: https://www.hkex.com.hk/Services/Trading/Derivatives/Overview/Trading-Calendar-and-Holiday-Schedule?sc_lang=en

If you see otherwise, please open a new Issue and point to where I can find that 2021-04-06 is a holiday. Thanks!
