### ISSUE TITLE
January 1st, 2022 is incorrectly marked as a holiday for NYSE

### ISSUE THREAD

**Issue by davraamides** [rsheftel/pandas_market_calendars#158]
January 1st, 2022 is marked as a holiday in the NYSE calendar but it is not actually a holiday according to the NYSE: https://www.nyse.com/markets/hours-calendars

Additionally, January 1st falls on a Saturday in 2022 so I wouldn't expect a holiday to fall on a weekend (for the purposes of business day calculations).

**Comment by glossner** [comment]
@davraamides  I'm not sure which version of pandas_market_calendars you are using. The NYSE calendar in the current respository doesn't consider Jan 1st, 2022 a holiday.

I believe that has been true since release 2.1. I'm closing this issue but feel free to reopen it if you are seeing this behavior in the 3.0 release. I just ran the tests again and it is not a holiday.
