### ISSUE TITLE
Missing Holidays

### ISSUE THREAD

**Issue by bacharsam** [rsheftel/pandas_market_calendars#177]
I noticed many HOLIDAYs are missing - e.g. :
'1994-01-01'
'2000-01-01'
'2005-01-01'
'2011-01-01'
'2022-01-01'

**Comment by glossner** [comment]
@bacharsam  what calendar?

**Comment by glossner** [comment]
@bacharsam It may also be helpful to note that for the purpose of a trading calendar, a holiday is defined as a day the market would have otherwise been open but was closed due to some event.

2022-01-01 is a Saturday. The market would have naturally been closed and therefore from the point of view of trading it is not  holiday.

I'm closing this out but if you think it is in error please feel free to reopen the issue.
