### ISSUE TITLE
Cannot change frequency to multiple days

### ISSUE THREAD

**Issue by dyus1983** [rsheftel/pandas_market_calendars#19]
My code is:
```
from pandas.tseries.offsets import DateOffset

tz = pytz.timezone('US/Eastern')
now_tz = datetime.datetime.now(tz)

dt_end = now_tz
dt_start = dt_end - DateOffset(days=50)

mkt_cal = mcal.get_calendar('NYSE')

schedule = mkt_cal.schedule(dt_start, dt_end)
bar_dts = mcal.date_range(schedule, frequency='3D')
```
The output shows that the frequency is 1 day, not 3 days:
`bar_dts`
DatetimeIndex(['2017-09-05 20:00:00+00:00', '2017-09-06 20:00:00+00:00',
               '2017-09-07 20:00:00+00:00', '2017-09-08 20:00:00+00:00',
               '2017-09-11 20:00:00+00:00', '2017-09-12 20:00:00+00:00',
               '2017-09-13 20:00:00+00:00', '2017-09-14 20:00:00+00:00',
               '2017-09-15 20:00:00+00:00', '2017-09-18 20:00:00+00:00',
               '2017-09-19 20:00:00+00:00', '2017-09-20 20:00:00+00:00',
               '2017-09-21 20:00:00+00:00', '2017-09-22 20:00:00+00:00',
               '2017-09-25 20:00:00+00:00', '2017-09-26 20:00:00+00:00',
               '2017-09-27 20:00:00+00:00', '2017-09-28 20:00:00+00:00',
               '2017-09-29 20:00:00+00:00', '2017-10-02 20:00:00+00:00',
               '2017-10-03 20:00:00+00:00', '2017-10-04 20:00:00+00:00',
               '2017-10-05 20:00:00+00:00', '2017-10-06 20:00:00+00:00',
               '2017-10-09 20:00:00+00:00', '2017-10-10 20:00:00+00:00',
               '2017-10-11 20:00:00+00:00', '2017-10-12 20:00:00+00:00',
               '2017-10-13 20:00:00+00:00', '2017-10-16 20:00:00+00:00',
               '2017-10-17 20:00:00+00:00', '2017-10-18 20:00:00+00:00',
               '2017-10-19 20:00:00+00:00', '2017-10-20 20:00:00+00:00',
               '2017-10-23 20:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='B')

Setting frequency to '1W' also yields 1-day frequency data.
What is wrong?

**Comment by rsheftel** [comment]
Because of the way the date_range() function works is that it takes in the output of the schedule and converts to a range. Since the schedule() method always returns the open and close for each day, the date_range() function can only return frequency of 1D or less (this now checks that the frequency passed in is valid).

To solve your problem I added a new function convert_freq() that takes the output of the date_range() and converts to a lower frequency like 1W or 3D in your example. So it is a two-step process, make the date_range() with frequency=1D, then convert to the desired lower frequency. Perhaps in the future I will put it all into the date_range(), but for now this solves your problem.

Please see the test_date_range_lower_freq() in test_utils.py for an example.
