### ISSUE TITLE
New stock exchange?

### ISSUE THREAD

**Issue by yangli0127** [rsheftel/pandas_market_calendars#40]
Hi all,

This is a great package! I am currently tracking business days for NYSE, JPX, and TSX by using this package. 

However, I am also tracking other stock exchanges, Australian Securities Exchange (ASX) and South Africa (JSE). I have to use other packages to track business days for these two stock exchanges specifically, which is not very convenient. Is it possible to add these two stock exchanges in this package in the future?

Thanks again for your significant contribution. It really helps!

Best regards,
Yang

**Comment by rsheftel** [comment]
Thanks for the compliment. 

If you would like to add a new market or exchange that would be great! The instructions on how to add are here: http://pandas-market-calendars.readthedocs.io/en/latest/new_market.html  It is also best to take the NYSE module (since that is the most complete) and use as template for a new exchange.

If you could do that with tests and submit a PR I will merge in. Thanks.
