### ISSUE TITLE
(Question)Where is the best place to add economic events with start and end time?  

### ISSUE THREAD

**Issue by bryanfok** [rsheftel/pandas_market_calendars#7]
Where is the best place to add economic events with start and end time?  Sometimes, not just holidays, we want to avoid trading during some economic events, e.g. Yellen speak. And we want to add those events to the calendar too.

**Comment by rsheftel** [comment]
That is a great question. Because the MarketCalendar() is about times when the market is open we would need an inverse class that as about when the market is closed. I think we do the following:

1. create a new abstract class EventCalendar()
2. the EventCalendar() class has methods for:
2a) "regular_events()" where that is a tuple of pandas AbstractHolidayClass that defines the event days and a datetime of the time of the event.
2b) "adhoc_events()" which is a list of dicts, where the key is the regular event date and the value is the datetime of the event. This is for events that sometimes move to non-standard dates like non-farm payrolls when they would fall on an early close date
2c) the "schedule()" method would now take a start and end time where that defined the window around the event that you want excluded.
2d) schedule dataframe would return the "event_start" and "event_end"
3. then in the utils create another version of the merge_schedules() function to take in multiple event schedules and create a combined list of all.
4. then in the utils another version of "date_range()" which will take that schedule and for a given frequency return a date_range of all of the datetimes that are inside the event window. Need to think if the frequency bucket chosen has some of the event window, does that exclude the entire datetime or not.
5. Now that we have the date_range of times we want to exclude, another function "merge_market_and_events" (needs a better name) that takes a date_range from the MarketCalendar and a date_range from the EventCalendar. Then use pandas to exclude from the MarketCalendar date range the values in the EventCalendar date range.

I will probably get around to implementing this at some point, but not immediately. If you want to get started with a pull request that can accelerate the process.  thx.

**Comment by bryanfok** [comment]
I think what I might do now would be add the capability to add events to the Calendar the way that you have described, but I will skip the part that do the event filtering part for the market calendar. The reason is what to do with the events are very different depend on users, and markets etc. Agree?

**Comment by bryanfok** [comment]
After investigate a bit more, i find the above implementation suggestion does not fit the reality,

1) all the events are not regular (e.g. brexit ) or semi-regular (e.g. Fed Chair Press Conference which schedule can be review yearly).  Which mean all of them, unlike holidays, are not computational, but rather ad-hoc bases.

2) From point 1, we can say that statically adding these events like MarketCalendar class are not scalable, and performance will be bad when the number of events increase.

One suggestion would be having a data source repository interface for querying the events by date ranges and return a dataframe for the result. And this would be deviated from the design of this library already....

**Comment by rsheftel** [comment]
The solution I was proposing is for event that would have been known in advance at the time for simulation (economic event, central bank speeches, etc.) and will be known in the future.

For surprise events like Brexit I agree that is out of scope for this project. My suggestion for that is to store them in a repository somewhere and use the pandas DateTimeIndex functionality to exclude them from the date ranges that this packages produces.

**Comment by rsheftel** [comment]
Thinking about this some more I think that this should be a separate module or package ("pandas_economic_events"?). Looking around there appear to be ways to grab economic calendars from the Fed and other online sources, so perhaps that can be the data repository. Then the relevant output could be a time series where the value is the time until / since the next / last event. This can be used by algo trading systems that need to get flat or alter behavior around events.

**Comment by drusakov778** [comment]
yes, very nice idea indeed. and Thanks for the project, I am now starting to use it
